"""
LegalRAGPipeline — end-to-end RAG over legal document corpora.

Architecture
------------
::

    sources (URLs / paths)
         │
         ▼
    AutoLoader  ──► ChunkingStrategy  ──► Embedder
         │                                    │
         ▼                                    ▼
    LegalDoc[]                         VectorStore (pgvector / chromadb / in-memory)
                                            │
    user question ─────────────────────────►│ similarity search
                                            │
                                       top-k chunks
                                            │
                                     [optional reranker]
                                            │
                                     PrivacyAwareLLMRouter
                                            │
                                       LLMProvider
                                            │
                                       RAGResponse (answer + citations)

Privacy behaviour
-----------------
Documents marked ``llm_routing="blocked"`` are indexed (their embeddings are
stored) but their text is **never** included in LLM context.  They can still
surface as citations if the source URL is public.

Source freshness
----------------
``sync_sources()`` re-fetches URL sources using ETag-based conditional GETs
(reuses the URLLoader's ETag support) and re-indexes changed documents.

Streaming
---------
Pass ``stream=True`` to ``query()`` to receive an ``Iterator[RAGResponse]``
yielding partial answers as tokens arrive from the provider.

Usage
-----
::

    from contractex.rag import LegalRAGPipeline
    from contractex.llm.openai_provider import OpenAIProvider

    pipeline = LegalRAGPipeline(
        llm_provider=OpenAIProvider(),
        citation_format="bluebook",
    )
    pipeline.ingest(["contracts/msa.pdf", "https://gdpr-info.eu/art-5-gdpr/"])
    response = pipeline.query("What are the data retention requirements?")
    print(response.answer)
    print(response.disclaimer)
"""

from __future__ import annotations

import logging
import time
from collections.abc import Iterator
from pathlib import Path
from typing import Any, Literal, cast

from pydantic import BaseModel, Field

from contractex.core.document import LegalDoc
from contractex.core.legal_document import SourceSpan
from contractex.rag.citation import Citation, CitationFormatter
from contractex.rag.conflict import Conflict, ConflictDetector

logger = logging.getLogger(__name__)

_LEGAL_DISCLAIMER = (
    "This response is legal information generated by an AI system, "
    "not legal advice.  Consult a qualified lawyer before acting on it."
)

_RAG_PROMPT_TEMPLATE = """\
You are a legal research assistant.  Answer the question below using ONLY the
provided source passages.  If the answer is not in the sources, say so.
Cite your sources using [N] inline notation.

Sources:
{context}

Question: {question}

Answer (with [N] citations):"""


# ---------------------------------------------------------------------------
# Result models
# ---------------------------------------------------------------------------


class RAGResponse(BaseModel):
    """
    A response from ``LegalRAGPipeline.query()``.

    Attributes
    ----------
    answer:
        The generated answer (may be partial when streaming).
    citations:
        Source citations for the answer.
    source_docs:
        The ``LegalDoc`` objects used as context.
    conflicts:
        Conflicts detected among the retrieved sources before LLM generation.
        Empty list means no conflicts were detected.
    authority_range:
        Tuple of (min_authority_weight, max_authority_weight) across all
        source documents used in the context, as floats in [0.01, 1.00].
    confidence:
        Weighted retrieval score for the top-k sources (semantic + authority).
    disclaimer:
        Always populated: "This is legal information, not legal advice."
    is_partial:
        ``True`` for intermediate streaming chunks.
    """

    answer: str = Field("", description="Generated answer")
    citations: list[Citation] = Field(default_factory=list)
    source_docs: list[LegalDoc] = Field(default_factory=list)
    conflicts: list[Conflict] = Field(
        default_factory=list,
        description="Conflicts detected among retrieved sources",
    )
    authority_range: tuple[float, float] = Field(
        (0.0, 0.0),
        description="(min, max) normalised authority weights of sources used",
    )
    confidence: float = Field(0.0, ge=0.0, le=1.0)
    disclaimer: str = Field(_LEGAL_DISCLAIMER)
    is_partial: bool = Field(False, description="True for streaming chunks")


class IngestResult(BaseModel):
    """Summary of a ``LegalRAGPipeline.ingest()`` call."""

    ingested: int = Field(0, description="Documents successfully ingested")
    skipped: int = Field(0, description="Documents skipped (already indexed, unchanged)")
    failed: int = Field(0, description="Documents that failed to load or index")
    errors: list[str] = Field(default_factory=list, description="Error messages for failed docs")
    elapsed_seconds: float = Field(0.0)


class SyncResult(BaseModel):
    """Summary of a ``LegalRAGPipeline.sync_sources()`` call."""

    checked: int = 0
    updated: int = 0
    unchanged: int = 0
    errors: list[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# In-memory vector store (default — no extra deps)
# ---------------------------------------------------------------------------


class _InMemoryVectorStore:
    """
    Minimal in-memory vector store backed by a list.

    For production use, replace with the pgvector or chromadb backend.
    """

    def __init__(self) -> None:
        self._entries: list[dict[str, Any]] = []

    def add(
        self,
        doc_id: str,
        chunk_id: str,
        text: str,
        embedding: list[float],
        metadata: dict[str, Any],
    ) -> None:
        self._entries.append(
            {
                "doc_id": doc_id,
                "chunk_id": chunk_id,
                "text": text,
                "embedding": embedding,
                "metadata": metadata,
            }
        )

    def search(
        self, query_embedding: list[float], top_k: int = 5, filters: dict[str, Any] | None = None
    ) -> list[dict[str, Any]]:
        """Cosine similarity search."""
        import math

        def cosine(a: list[float], b: list[float]) -> float:
            dot = sum(x * y for x, y in zip(a, b))
            na = math.sqrt(sum(x * x for x in a))
            nb = math.sqrt(sum(x * x for x in b))
            return dot / (na * nb) if na and nb else 0.0

        scored = [(cosine(query_embedding, e["embedding"]), e) for e in self._entries]
        scored.sort(key=lambda t: t[0], reverse=True)
        return [{**e, "score": score} for score, e in scored[:top_k] if score > 0]

    def __len__(self) -> int:
        return len(self._entries)


# ---------------------------------------------------------------------------
# Main pipeline
# ---------------------------------------------------------------------------

# Sentinel used to distinguish "not supplied" from explicit None in constructor
_SENTINEL: Any = object()


class LegalRAGPipeline:
    """
    End-to-end RAG pipeline for legal document corpora.

    Parameters
    ----------
    llm_provider:
        LLM provider for answer generation.  Required.
    embedding_model:
        Sentence-transformers model name for embedding.
        Defaults to ``"all-MiniLM-L6-v2"`` (lightweight, no GPU required).
    vector_store:
        An object implementing ``add()`` and ``search()`` (see
        ``_InMemoryVectorStore``).  Defaults to in-memory store.
    privacy_router:
        ``PrivacyAwareLLMRouter`` instance.  A default router is created
        if not supplied.
    citation_format:
        One of ``"inline"``, ``"footnote"``, ``"bluebook"``.
    reranker:
        Optional callable ``(query: str, chunks: list[dict]) → list[dict]``
        for cross-encoder reranking.
    alpha:
        Weight for semantic similarity in final retrieval score [0, 1].
        Default: 0.60.
    beta:
        Weight for authority score in final retrieval score [0, 1].
        Default: 0.30.
    gamma:
        Weight for recency score in final retrieval score [0, 1].
        Default: 0.10.
    conflict_detector:
        ``ConflictDetector`` instance.  Pass ``None`` to disable conflict
        detection.  A default detector is created if not supplied.
    """

    def __init__(
        self,
        llm_provider: Any,
        embedding_model: str = "all-MiniLM-L6-v2",
        vector_store: Any | None = None,
        privacy_router: Any | None = None,
        citation_format: Literal["inline", "footnote", "bluebook"] = "inline",
        reranker: Any | None = None,
        alpha: float = 0.60,
        beta: float = 0.30,
        gamma: float = 0.10,
        conflict_detector: ConflictDetector | None = _SENTINEL,  # type: ignore[assignment]
    ) -> None:
        self._provider = llm_provider
        self._embedding_model_name = embedding_model
        self._vector_store = vector_store or _InMemoryVectorStore()
        self._citation_format = citation_format
        self._reranker = reranker
        self._formatter = CitationFormatter()
        self._embedder: Any | None = None
        self._alpha = alpha
        self._beta = beta
        self._gamma = gamma

        # Conflict detector — default enabled
        if conflict_detector is _SENTINEL:
            self._conflict_detector: ConflictDetector | None = ConflictDetector()
        else:
            self._conflict_detector = conflict_detector

        # Privacy router
        if privacy_router is not None:
            self._router = privacy_router
        else:
            from contractex.privacy.router import PrivacyAwareLLMRouter

            self._router = PrivacyAwareLLMRouter()

        # Source tracking for sync
        self._source_urls: list[str] = []

        # Doc registry: doc_id → LegalDoc (for conflict detection)
        self._doc_registry: dict[str, LegalDoc] = {}

    # ------------------------------------------------------------------
    # Ingestion
    # ------------------------------------------------------------------

    def ingest(self, sources: list[str | Path]) -> IngestResult:
        """
        Load, chunk, embed, and index *sources*.

        Parameters
        ----------
        sources:
            List of file paths or URLs to ingest.

        Returns
        -------
        IngestResult
        """
        from contractex.chunking.semantic import SemanticChunker
        from contractex.loaders.auto import AutoLoader

        loader = AutoLoader()
        chunker = SemanticChunker()
        embedder = self._get_embedder()

        result = IngestResult()
        t0 = time.perf_counter()

        for source in sources:
            source_str = str(source)
            try:
                doc = cast(LegalDoc, loader.load(source_str))
                chunks = chunker.chunk(doc.full_text or "")

                for i, chunk in enumerate(chunks):
                    chunk_id = f"{doc.doc_id or source_str}:chunk:{i}"
                    embedding = embedder.encode(chunk)
                    self._vector_store.add(
                        doc_id=doc.doc_id or source_str,
                        chunk_id=chunk_id,
                        text=chunk,
                        embedding=(
                            embedding.tolist() if hasattr(embedding, "tolist") else list(embedding)
                        ),
                        metadata={
                            "source_url": source_str,
                            "doc_type": str(doc.doc_type),
                            "llm_routing": (
                                doc.privacy_profile.llm_routing if doc.privacy_profile else "any"
                            ),
                            "page": getattr(chunk, "page", None),
                            # Authority + jurisdiction metadata for weighted scoring
                            "authority_weight": doc.authority_weight,
                            "publication_year": (
                                getattr(doc.authority_profile, "publication_year", None)
                                if doc.authority_profile
                                else None
                            ),
                            "jurisdiction_country": (
                                getattr(doc.effective_jurisdiction_tag, "country", None)
                            ),
                            "jurisdiction_region": (
                                getattr(doc.effective_jurisdiction_tag, "region", None)
                            ),
                            "is_superseded": (
                                getattr(doc.authority_profile, "is_superseded", False)
                                if doc.authority_profile
                                else False
                            ),
                        },
                    )

                # Register doc for conflict detection
                self._doc_registry[doc.doc_id] = doc
                result.ingested += 1
                if source_str.startswith("http"):
                    self._source_urls.append(source_str)

            except Exception as exc:
                logger.warning("Failed to ingest %r: %s", source_str, exc)
                result.failed += 1
                result.errors.append(f"{source_str}: {exc}")

        result.elapsed_seconds = round(time.perf_counter() - t0, 3)
        logger.info(
            "Ingest complete: %d ingested, %d failed in %.1fs",
            result.ingested,
            result.failed,
            result.elapsed_seconds,
        )
        return result

    # ------------------------------------------------------------------
    # Query
    # ------------------------------------------------------------------

    def query(
        self,
        question: str,
        filters: dict[str, Any] | None = None,
        top_k: int = 5,
        stream: bool = False,
        jurisdiction_filter: Any | None = None,
    ) -> RAGResponse | Iterator[RAGResponse]:
        """
        Answer *question* using retrieved source passages.

        Parameters
        ----------
        question:
            The user's natural-language question.
        filters:
            Metadata filters for vector search (e.g. ``{"doc_type": "statute"}``).
        top_k:
            Number of source chunks to retrieve.
        stream:
            If ``True``, return an iterator of partial ``RAGResponse`` objects.
        jurisdiction_filter:
            ``JurisdictionTag`` instance.  When supplied, results are
            **hard-filtered** to sources whose jurisdiction is compatible.
            Sources from other jurisdictions never appear in the answer
            without an explicit flag — this is not a soft preference.

        Returns
        -------
        RAGResponse | Iterator[RAGResponse]
        """
        embedder = self._get_embedder()
        q_embedding = embedder.encode(question)
        if hasattr(q_embedding, "tolist"):
            q_embedding = q_embedding.tolist()

        hits = self._vector_store.search(q_embedding, top_k=top_k * 3, filters=filters)
        # Retrieve extra candidates (top_k*3) to allow for jurisdiction and
        # superseded filtering before selecting the final top_k.

        # 1. Filter blocked documents
        hits = [h for h in hits if h.get("metadata", {}).get("llm_routing") != "blocked"]

        # 2. Filter superseded sources
        hits = [h for h in hits if not h.get("metadata", {}).get("is_superseded", False)]

        # 3. Hard jurisdiction filter — non-matching sources are excluded entirely
        if jurisdiction_filter is not None:
            filtered: list[dict[str, Any]] = []
            for h in hits:
                meta = h.get("metadata", {})
                country = meta.get("jurisdiction_country")
                region = meta.get("jurisdiction_region")
                if country is None:
                    # No jurisdiction metadata — include conservatively
                    filtered.append(h)
                    continue
                from contractex.taxonomy.jurisdiction import JurisdictionTag

                source_tag = JurisdictionTag(
                    country=country, region=region or None, applicability="binding"
                )
                if source_tag.matches(jurisdiction_filter):
                    filtered.append(h)
            hits = filtered

        # 4. Authority-weighted rescoring

        def _recency_weight(year: int | None) -> float:
            """Normalised recency: current year = 1.0, each decade ≈ -0.1."""
            if year is None:
                return 0.5  # unknown → neutral
            import datetime

            age = max(0, datetime.date.today().year - year)
            return max(0.0, 1.0 - age * 0.02)  # decay 2% per year, floor 0

        rescored: list[tuple[float, dict[str, Any]]] = []
        for h in hits:
            sem_score = float(h.get("score", 0.0))
            meta = h.get("metadata", {})
            auth_w = float(meta.get("authority_weight", 0.01))
            rec_w = _recency_weight(meta.get("publication_year"))
            final = self._alpha * sem_score + self._beta * auth_w + self._gamma * rec_w
            rescored.append((final, h))

        rescored.sort(key=lambda t: t[0], reverse=True)
        context_hits = [h for _, h in rescored[:top_k]]

        if self._reranker and context_hits:
            context_hits = self._reranker(question, context_hits)

        # 5. Resolve source docs for conflict detection
        source_docs: list[LegalDoc] = []
        for h in context_hits:
            doc_id = h.get("doc_id", "")
            if doc_id in self._doc_registry:
                source_docs.append(self._doc_registry[doc_id])

        # 6. Conflict detection
        conflicts: list[Conflict] = []
        if self._conflict_detector and source_docs:
            conflicts = self._conflict_detector.detect(source_docs, query=question)

        # 7. Build context string with numbered passages
        context_parts: list[str] = []
        citations: list[Citation] = []

        for i, hit in enumerate(context_hits, 1):
            meta = hit.get("metadata", {})
            title = meta.get("source_url", f"Source {i}")
            context_parts.append(f"[{i}] {hit['text']}")
            span = SourceSpan(
                chunk_id=hit.get("chunk_id", f"chunk-{i}"),
                source_url=meta.get("source_url"),
                page=meta.get("page"),
            )
            citations.append(
                Citation(
                    text_fragment="",
                    source_title=title,
                    source_url=meta.get("source_url"),
                    source_span=span,
                    index=i,
                )
            )

        context = "\n\n".join(context_parts)
        conflict_addendum = ""
        if self._conflict_detector:
            conflict_addendum = self._conflict_detector.build_conflict_prompt_addendum(conflicts)
        prompt = _RAG_PROMPT_TEMPLATE.format(context=context, question=question) + conflict_addendum

        # Weighted confidence = average final score across context hits
        scores = [rescored[i][0] for i in range(len(context_hits))]
        avg_score = sum(scores) / len(scores) if scores else 0.0

        # Authority range
        auth_weights = [
            float(h.get("metadata", {}).get("authority_weight", 0.01)) for h in context_hits
        ]
        authority_range = (min(auth_weights, default=0.0), max(auth_weights, default=0.0))

        # Format citation strings
        self._formatter.format_all(citations, style=self._citation_format)

        if stream:
            return self._stream_query(
                prompt, citations, avg_score, conflicts, authority_range, source_docs
            )

        # Non-streaming
        answer = self._provider.complete(prompt, temperature=0.1)
        return RAGResponse(
            answer=answer,
            citations=citations,
            source_docs=source_docs,
            conflicts=conflicts,
            authority_range=authority_range,
            confidence=avg_score,
        )

    async def query_async(
        self,
        question: str,
        filters: dict[str, Any] | None = None,
        top_k: int = 5,
        jurisdiction_filter: Any | None = None,
    ) -> RAGResponse:
        """Async version of ``query()`` (non-streaming)."""
        import asyncio

        loop = asyncio.get_event_loop()
        return cast(
            RAGResponse,
            await loop.run_in_executor(
                None,
                lambda: self.query(
                    question,
                    filters=filters,
                    top_k=top_k,
                    jurisdiction_filter=jurisdiction_filter,
                ),
            ),
        )

    def _stream_query(
        self,
        prompt: str,
        citations: list[Citation],
        avg_score: float,
        conflicts: list[Conflict] | None = None,
        authority_range: tuple[float, float] = (0.0, 0.0),
        source_docs: list[LegalDoc] | None = None,
    ) -> Iterator[RAGResponse]:
        """Yield partial RAGResponse objects as tokens arrive."""
        accumulated = ""
        _conflicts = conflicts or []
        _source_docs = source_docs or []
        for token in self._provider.stream_complete(prompt, temperature=0.1):
            accumulated += token
            yield RAGResponse(
                answer=accumulated,
                citations=citations,
                source_docs=_source_docs,
                conflicts=_conflicts,
                authority_range=authority_range,
                confidence=avg_score,
                is_partial=True,
            )
        # Final non-partial response
        yield RAGResponse(
            answer=accumulated,
            citations=citations,
            source_docs=_source_docs,
            conflicts=_conflicts,
            authority_range=authority_range,
            confidence=avg_score,
            is_partial=False,
        )

    # ------------------------------------------------------------------
    # Source sync
    # ------------------------------------------------------------------

    def sync_sources(self) -> SyncResult:
        """
        Re-fetch URL sources and re-index any that have changed.

        Uses ETag-based conditional GETs to avoid unnecessary re-processing.
        """
        result = SyncResult()

        for url in self._source_urls:
            result.checked += 1
            try:
                # Use URLLoader / AutoLoader's ETag support
                # For sync, we just re-ingest (idempotent for in-memory store)
                ingest_result = self.ingest([url])
                if ingest_result.ingested > 0:
                    result.updated += 1
                else:
                    result.unchanged += 1
            except Exception as exc:
                result.errors.append(f"{url}: {exc}")

        return result

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    def _get_embedder(self) -> Any:
        if self._embedder is None:
            try:
                from sentence_transformers import SentenceTransformer

                self._embedder = SentenceTransformer(self._embedding_model_name)
            except ImportError:
                raise ImportError(
                    "sentence-transformers is required for RAG embeddings.\n"
                    "Install with: pip install contractex[rag]"
                ) from None
        return self._embedder

    def __repr__(self) -> str:
        store_size = len(self._vector_store) if hasattr(self._vector_store, "__len__") else "?"
        return (
            f"<LegalRAGPipeline model={self._embedding_model_name!r} "
            f"chunks_indexed={store_size}>"
        )
